I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 8, in script
    image  rms neutral = stallman.jpg
  File "game/script.rpy", line 8, in <module>
    image  rms neutral = stallman.jpg
NameError: name 'stallman' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/sean/Workspace/Python/renpy/renpy/bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "/home/sean/Workspace/Python/renpy/renpy/main.py", line 419, in main
    game.context().run(node)
  File "game/script.rpy", line 8, in script
    image  rms neutral = stallman.jpg
  File "/home/sean/Workspace/Python/renpy/renpy/ast.py", line 907, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/home/sean/Workspace/Python/renpy/renpy/python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 8, in <module>
    image  rms neutral = stallman.jpg
NameError: name 'stallman' is not defined

Linux-4.12.0-13-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.12.4.2187
stallman 1.0
